### ISSUE TITLE
The upload of long acquisition files is slow.

### ISSUE THREAD

**Issue by fincardona** [lspestrip/stdb2#19]
The upload on the DB of the long acquisition files is slow. Is it possible to upload zip files for this kind of test? It would be useful to speed up the files loading. I tried this with the STRIP43 long acquisition but the plot doesn't appear in the test page [https://striptest.fisica.unimi.it/unittests/tests/68/](url) (even if the file is correctly uploaded)

**Comment by ziotom78** [comment]
It is possible to upload files in HDF5 format, which it's compressed using gzip and is therefore much more efficient. To create HDF5 files in the correct format, use the program `convert_to_hdf5.py` available in [stdb2](https://github.com/lspestrip/stdb2).

Note that the file for test 68 does not seem to have been uploaded correctly, as it is only 7 kB long.

**Comment by fincardona** [comment]
OK. Now it works. Thanks
