### ISSUE TITLE
Add "add test" button on the side navigation menu

### ISSUE THREAD

**Issue by fincardona** [lspestrip/stdb2#24]
To make easier finding the "add test" button it might be useful to add it on the side navigation bar (e.g. under "polarimetric tests")

**Comment by fincardona** [comment]
Actually it would be useful to add the "add test" button also in the page that contains all the tests of a given polarimeter (e.g. in this page [https://striptest.fisica.unimi.it/unittests/STRIP04/](url) )

**Comment by ziotom78** [comment]
The «add button» would look a bit out of place in the sidebar, as this is used to open pages which present the result of queries on the database and do not trigger actions. (I.e., all the actions in the sidebar do not require the user to be logged in).

However, I agree that it would be useful to have the button «Add test» in the polarimeter pages, so I implemented this change.

I'm going to close this bug, feel free to reopen it if you want to have the button appear anywhere else.
