### ISSUE TITLE
Add all polarimetric tests in the side bar

### ISSUE THREAD

**Issue by fincardona** [lspestrip/stdb2#25]
It would be very useful to show all the polarimetric tests in the side bar (e.g. under "polarimetric tests"). This will make faster and easier to copy and paste the json files between one test and another.

**Comment by ziotom78** [comment]
Not sure this is a good idea. The expected number of tests to be uploaded in the db is more than 500, the side bar would be really long. Isn't it better to keep each test you are referring to in a separate tab in your browser?

**Comment by fincardona** [comment]
Yes, maybe it is. I close this issue. Thanks Maurizio.
